<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{66d06c91-d797-4675-9bef-0baaaa0a4f7b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	prox_sensors: ARRAY [1..8] OF BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

prox_sensors := GVL_input.sensor;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="6" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="16" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>